name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Verify Java version
      run: java -version

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: List directory contents after chmod
      run: ls -la

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests with Gradle
      run: ./gradlew test

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v3
      with:
        name: test-results
        path: build/reports/tests/test

    - name: Build the Docker image
      if: always()
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
