name: Gradle Package

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Check out repository code
      uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        server-id: github
        settings-path: ${{ github.workspace }}

    - name: Verify Java version
      run: java -version

    - name: List directory contents before chmod
      run: ls -la

    - name: Print current directory
      run: pwd

    - name: Verify gradlew file
      run: |
        if [ ! -f ./gradlew ]; then
          echo "gradlew file not found"
          exit 1
        else
          echo "gradlew file found"
        fi

    - name: Grant execute permission for gradlew
      run: chmod +x ./gradlew

    - name: List directory contents after chmod
      run: ls -la

    - name: Verify gradlew permissions
      run: ls -la ./gradlew

    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2

    - name: Build with Gradle
      run: ./gradlew build

    - name: Run tests with Gradle
      run: ./gradlew test

    - name: Publish to GitHub Packages
      run: ./gradlew publish
      env:
        USERNAME: ${{ github.actor }}
        TOKEN: ${{ secrets.GITHUB_TOKEN }}
